### PR TITLE
fix(general): fix bootstrap

### PR DESCRIPTION
**Pull request by LeonVreling**

### CODE REVIEW

**Comment by WikiRik** [comment]
@serge1peshcoff @linuxbandit any clue why this helps with bootstrapping? If we don't add this (at Windows devices at least), it does not want to create the database. And is there maybe a nicer way to fix this?

**Comment by serge1peshcoff** [comment]
well it shouldn't help it, and if it does, this is super weird

**Comment by WikiRik** [comment]
I haven't tested putting in something else than this, but editing this file to include this helped mine and Leon's problems for some weird reason

**Comment by linuxbandit** [comment]
holy shit

**Comment by serge1peshcoff** [comment]
What I'd rather do instead of merging is investigating why this doesn't work without this command

**Comment by WikiRik** [comment]
@serge1peshcoff it most often occurs on statutory, but that might just be a coincidence. I've closed the other PRs so we can investigate before merging

**Comment by WikiRik** [comment]
https://github.com/AEGEE/MyAEGEE/pull/218

**Pull request closed without merging**
